site_name: coreason_arbitrage
theme:
  name: material
nav:
  - Home: index.md
  - Usage: usage.md
  - Requirements: requirements.md
  - Product Requirements: product_requirements.md
  - Technical Vignette: technical_vignette.md
